### ISSUE TITLE
Setting up Kanban Board

### ISSUE THREAD

**Issue by Boku52500** [Boku52500/Space-Travelers-Hub#25]
Team members:
@Boku52500 

Link to Kanban Board:
https://github.com/Boku52500/Space-Travelers-Hub/projects/2

Link to my dashboard screenshot:
https://gyazo.com/07b060c113bb9c3a5b2bd4bc2f29b4cd

NOTE: I am working on the project alone, since I do not have any coding partners for the week. I have assigned myself to do the missions part. Should I also do the rockets part? or just the missions part is going to work since I am doing this alone. Please leave me a note about this. Thank you in advance.

**Comment by franclobo** [comment]
Hi @Boku52500, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the link to the kanban board (GitHub project). Please 🙏🏽 paste the link to your kanban board and a picture of your dashboard that shows that you are alone this week. Answering your question in the case you are going to work alone you should work like you were a group of two members, it means you must complete the rockets and missions requirements, but no dragons.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by franclobo** [comment]
Hi @Boku52500, 

# STATUS: APPROVED 😄 

![gif-good-job-79](https://user-images.githubusercontent.com/58642949/210281546-31c28def-65ce-47c7-b1df-baf076f7b2a6.gif)

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- Good implementation of the Kanban board. ✔️
- Correct assignment of activities ✔️ 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
